packages/app/components/Questions/AsyncQuestions/AsyncCard.tsx, yarn.lock
I added voting back after it was accidentally removed
=> added voting back

packages/app/pages/login.tsx
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
=> Update login.tsx to Dima fix

packages/app/components/Settings/ChatbotQuestions.tsx, packages/app/components/Settings/ChatbotSettings.tsx, packages/app/components/Settings/EditChatbotQuestionModal.tsx, packages/app/components/Today/ChatbotToday.tsx, packages/server/src/login/login.controller.ts
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
=> Hot fix for chatbot related interface UI

docs/toggle_course_features_help.md, packages/app/components/Chatbot/Chatbot.tsx, packages/app/components/Nav/NavBar.tsx, packages/app/components/Questions/Queue/Queue.tsx, packages/app/components/Settings/CourseAdminPanel.tsx, packages/app/components/Settings/SettingsPage.tsx, packages/app/components/Settings/ToggleFeaturesPage.tsx, packages/app/hooks/useCourseFeatures.ts, packages/app/pages/course/[cid]/today.tsx, packages/app/pages/courses.tsx
This fixes a bunch of bugs that were bugging me:
- (Important) uploading user profile picture now works as expected
- it previously required multiple attempts to upload before it would do anything
- re-added a "You already have a question in a queue for this course. Please delete your previous question before joining this queue" error message if you're already in a queue
-  ('cause right now no feedback is shown at all). 
- (I may have introduced this error at some point)
- (Important) fixed the collapse menus on the user settings page so that they stop closing themselves
- had to do with how the useWindowSize react hook was used. When expanding the collapse menu, if it expands enough to extend the window size, it will cause an update to useWindowSize, causing the entire page to …
=> Small bug fixes

packages/api-client/index.ts, packages/app/pages/course/[cid]/invite.tsx, packages/app/pages/login.tsx, packages/app/pages/verify.tsx, packages/common/index.ts, packages/server/src/asyncQuestion/asyncQuestion.module.ts, packages/server/src/auth/auth.controller.ts, packages/server/src/common/helpers.ts, packages/server/src/course/course.controller.ts, packages/server/src/login/login.controller.ts, packages/server/src/profile/profile.controller.ts, packages/server/test/auth.integration.ts, packages/server/test/course.integration.ts
Fixes an issue where users were not redirected to invite link page when they created or signed in to an account
=> [Bug Fix] Invite link Redirect

packages/app/pages/courses.tsx
=> fix org card z level

packages/app/components/Organization/UsersTab.tsx, packages/app/components/Settings/CourseAdminPanel.tsx, packages/app/components/Settings/SettingsPage.tsx, packages/app/components/Today/QueueCheckInButton.tsx, packages/app/pages/organization/course/[cid]/edit.tsx, packages/app/pages/organization/settings.tsx, packages/app/pages/organization/user/[uid]/edit.tsx, packages/server/src/organization/organization.controller.ts
- Allows organization admins to change user roles in the organization
- Disables any course modifications on the front end when the user is not a professor in the organization
- Fixes an issue where code in the backend incorrectly handled async and await calls
- Fixes an issue where the empty user's last name of the user was displayed as `null` instead of an empty string
=> [Bug Fix / Feature] Allow admins to change user roles when sso is enabled for organization

packages/app/components/Settings/ChatbotSettings.tsx
Fixes issue https://github.com/ubco-db/helpme/issues/20, please visit issue for more details
=> [Bugfix / Feature] force user to wait until upload is completed and allow user to select delete multiple files

packages/app/pages/login.tsx, packages/server/src/auth/auth.controller.ts, packages/server/src/course/course.controller.ts, packages/server/src/login/login.controller.ts, packages/server/test/auth.integration.ts
Fixes an issue where encoded base64 cookie was incorrectly decoding the value on backend.
=> [Bug] Invite link encoding issue

docs/toggle_course_features_help.md, packages/common/index.ts, packages/frontend/app/(auth)/login/page.tsx, packages/frontend/app/(dashboard)/components/CourseFeaturesForm.tsx, packages/frontend/app/(dashboard)/components/EditCourse.tsx, packages/frontend/app/(dashboard)/course/[cid]/async_centre/components/AsyncQuestionCard.tsx, packages/frontend/app/(dashboard)/course/[cid]/async_centre/components/modals/CreateAsyncQuestionModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/async_centre/components/modals/PostResponseModal.tsx, packages/frontend/app/(dashboard)/organization/components/CoursesTable.tsx, packages/frontend/app/(dashboard)/organization/course/add/page.tsx, packages/frontend/app/api/index.ts, packages/server/src/course/course.controller.ts, packages/server/src/course/course_settings.entity.ts, packages/server/src/organization/__snapshots__/organization.service.spec.ts.snap, packages/server/src/organization/organization.controller.ts, packages/server/src/organization/organization.service.ts, packages/server/test/__snapshots__/organization.integration.ts.snap, packages/server/test/course.integration.ts, packages/server/test/organization.integration.ts
- Added asyncCentreAIAnswers and scheduleOnFrontPage courseFeatures with updated tests, toggles on the course page, and toggles on the course creation page
- Disabled captcha on dev
- Added a "archived" tag to courses on organization/courses
Just updated existing tests
=> New asyncCentreAIAnswers and scheduleOnFrontPage courseFeatures

packages/frontend/app/(dashboard)/course/[cid]/async_centre/components/modals/CreateAsyncQuestionModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/async_centre/utils/commonAsyncFunctions.ts
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
=> fix merge conflicts

packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx, packages/frontend/app/(dashboard)/organization/dev/page.tsx, packages/server/src/organization/organization.controller.ts
=> fix: rate limit does not apply to professor

packages/server/src/organization/organization.controller.ts, packages/server/test/organization.integration.ts
Added tests for issue 54
Closes # (54)
=> tests added for rate limit chatbot and subscriptions

packages/frontend/app/(dashboard)/components/EditCourseForm.tsx, packages/frontend/app/(dashboard)/components/organizationCard.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/layout.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/components/CourseRosterTable.tsx, packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx, packages/frontend/app/(dashboard)/course/[cid]/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/JoinTagGroupButton.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/QueueInfoColumn.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/TagGroupSwitch.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx, packages/frontend/app/(dashboard)/courses/page.tsx, packages/frontend/app/(dashboard)/layout.tsx, packages/frontend/app/(dashboard)/organization/components/SidebarNavigation.tsx, packages/frontend/app/components/HeaderBar.tsx, packages/frontend/app/hooks/useStudentAssignmentProgress.ts, packages/frontend/app/utils/generalUtils.ts, packages/frontend/middleware.ts
Read commit messages
Manual testing.
=> Misc Frontend Bug Fixes

docs/NEWDEVS_STARTHERE.md, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/check_in/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/async_centre/components/modals/CreateAsyncQuestionModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/async_centre/utils/commonAsyncFunctions.ts, packages/frontend/app/(dashboard)/course/[cid]/components/QuestionTagElement.tsx, packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx, packages/frontend/app/utils/generalUtils.ts, packages/server/migration/1726179810316-question-types-soft-delete.ts, packages/server/src/calendar/calendar.controller.ts, packages/server/src/course/course.entity.ts, packages/server/src/questionType/question-type.entity.ts, packages/server/src/questionType/questionType.controller.ts, packages/server/src/queue/__snapshots__/queue.service.spec.ts.snap, packages/server/test/__snapshots__/queue.integration.ts.snap, packages/server/test/question.integration.ts, packages/server/test/questionType.integration.ts
Changes delete question type to a soft delete (sets a deletedAt field)
Read commit messages for the other small fixes
Closes #98 
I have added a new test to ensure the endpoint soft deletes the question types.
I have manually tested creating/deleting question types in both queues and anytime question hub and everything still seems to work as normal.
=> Question Type Soft Deletion, Student update/delete async question fix, + other small fixes

packages/server/src/organization/organization.controller.ts, packages/server/test/organization.integration.ts
This PR addresses an issue where Teaching Assistants (TAs) were not receiving the correct subscription types.
Previously, the system only checked the user's role in the organization_user_model, which didn't account for users who are TAs in specific courses but regular members in the organization.
Changes:
- Modified the query to check for TA roles in user_course_model
- Updated subscription logic to treat TAs like professors for subscription purposes
- Added test cases to verify correct subscription assignment for TAs and regular members
This fix ensures that users who are TAs in any course receive the same subscription privileges as professors, even if they are listed as regular members in the organization.
Please describe how you tested this PR (both manually and …
=> Correct Subscription Handling for TAs

packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/QuestionCard.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/QueueQuestions.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/StudentBanner.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx, packages/frontend/app/components/HeaderBar.tsx
- Now the queues show the questions that are currently being helped with a timer for how long they have been helped
It also gets shown on the TA side so they know how long they have been helping a student
- Fixed the header bar text being too big with certain courses/queues
Just the usual manual testing.
=> Now being served + other UI fixes

packages/frontend/app/(dashboard)/course/[cid]/schedule/components/CreateEventModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/schedule/components/EditEventModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/schedule/components/TASchedulePanel.tsx
See commit messages.
Closes #107 
Manually tested creating event with modal and with click + drag
=> Create Event Button

packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/TAQuestionCardButtons.tsx, packages/server/src/question/question.service.ts
Closes #128 
Manually tested helping an unfinished demo
=> fixed bug soft locking you if you start helping an unfinished demo

packages/frontend/app/(dashboard)/course/[cid]/layout.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/CircleButton.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/TAQuestionCardButtons.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/modals/StudentRephraseModal.tsx, packages/frontend/app/components/AlertsContainer.tsx
Closes #138 and #139
Manually tested each button
=> Re-add Rephrase Modal and add loading to question card buttons

packages/frontend/app/(dashboard)/components/FooterBar.tsx, packages/frontend/app/(dashboard)/components/coursesSection.tsx, packages/frontend/app/(dashboard)/layout.tsx, packages/frontend/app/layout.tsx
Just sticks a footer bar on the end of the page with my work email on it.
As a bonus this also changes the tag color of the role on /courses so that it's not all green.
Closes #102 
Since this required changing everything to flex, I checked EVERY page on desktop on mobile to make sure nothing broke, and it looks like everything is working as expected.
=> User feedback footer

packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/components/CourseRosterTable.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/roster/page.tsx, packages/frontend/app/(dashboard)/organization/components/UsersTable.tsx, packages/server/src/organization/organization.controller.ts, packages/server/test/organization.integration.ts
NOTE: you can only remove users from your course if you are an organization admin or organization professor
Closes #114 
I tried elevated TaOne to an organization professor, had them create a course, invited studentOne to the course, and then used TaOne to remove studentOne from the course.
=> Remove user from my course button

packages/frontend/app/(dashboard)/course/[cid]/components/QueueCard.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/StaffList.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/TAQuestionCardButtons.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx, packages/server/src/question/question.controller.ts, packages/server/src/question/question.service.ts, packages/server/test/question.integration.ts
This was surprisingly easy to do. I literally just removed the checks for it and the system worked fine. I adjusted a couple UI components and added a "finish helping all" button.
Closes #141 
Just manual testing.
=> TAs help multiple students at same time

packages/frontend/app/(dashboard)/course/[cid]/components/QuestionTagElement.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/QueueQuestions.tsx, packages/frontend/app/globals.css
before
after
new animated border, see discord for videos
Manual testing.
=> Change rainbow border and Question Tag sorting fix

packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/modals/CreateQuestionModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/modals/EditQueueModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx
All the backend was already there for it. Just needed to make it do something on the frontend.
Closes #135 
Manually tested creating questions with minimum 0, 1, and 3 tags.
Also tried updating the minimum question tags various different ways.
=> Minimum Question Tags

packages/frontend/app/(dashboard)/course/[cid]/components/TACheckinButton.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/modals/AssignmentReportModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/modals/CreateDemoModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/modals/CreateQuestionModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx
Read commit messages
Manual testing.
=> Adds some more loading states to some buttons

package.json, packages/frontend/app/(auth)/login/page.tsx, packages/frontend/app/(dashboard)/layout.tsx, packages/frontend/app/api/organizationApi.ts, packages/frontend/app/error_pages/429/page.tsx, packages/frontend/middleware.ts, packages/server/package.json, packages/server/src/app.module.ts, packages/server/src/backup/backup.service.ts, packages/server/src/bootstrap.ts, packages/server/src/exception_filters/429-exception.filter.ts, packages/server/src/login/login.controller.ts, packages/server/src/profile/profile.controller.ts, yarn.lock
Fixes some issues with the login page (see #177)
The biggest thing here is this prevents brute-force attacks (since there was previously nothing stopping malicious users from just calling the login endpoint with every password, which is really bad).
Also I guess this gives some DoS protection now with the throttler. 
Note that the rate throttler does not apply to GET /profile since the middleware calls that endpoint a crap load (basically every time a link appears)
Closes #177 
I've tested lowering the rate throttler a lot to see what happens when certain things get rate throttled. Usually, some weird stuff happens, and it's kinda impossible to go through and have an edge case check for all of these, but I don't think it will be much of an issue for users since I don't think any of our UI …
=> Rate Throttler + Login Fixes

packages/frontend/app/(auth)/verify/page.tsx, packages/server/src/auth/auth.controller.ts
Closes #218 
Manually tested putting in lowercase 'a's and they get sent in uppercase.
=> fixed verify code being case sensitive

packages/server/src/calendar/calendar.service.spec.ts, packages/server/src/calendar/calendar.service.ts, packages/server/src/course/course.service.ts, packages/server/test/course.integration.ts
Fixes a couple important bugs (see commit messages)
Manually tested getting auto checked out in a few cases. Also added a new integration test.
=> (Important pls merge) Auto Checkout Bug Fixes

packages/common/index.ts, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/modals/AssignmentReportModal.tsx
Adds sorting by time, name, or by sid to the assignment report modal (previously it was only by time) with ASC and DESC
Closes #160 
Manually tested. With 3 student accounts I tried all combinations of sorting and it all works. Also tried when the student id is undefined
=> Assignment Report Modal Sorting

packages/frontend/public/userguide.md
=> User Guide for chatbot

packages/frontend/app/(dashboard)/components/AddChatbot.tsx, packages/frontend/app/(dashboard)/course/[cid]/(insights)/layout.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/layout.tsx, packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx, packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/ChatbotProvider.tsx, packages/frontend/app/(dashboard)/course/[cid]/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/schedule/page.tsx, packages/frontend/app/typings/chatbot.ts, packages/frontend/app/utils/generalUtils.ts, packages/frontend/dev.env
Adds a "System" chatbot.
So there's a lot of different ways to get the userguide to the chatbot, but this is by far the easiest.
Basically, you must first create a "HelpMe" **course** where you upload the chatbot. Then, give the user a toggle that lets them ask "System" questions, which will then send the question to the "HelpMe" course.
Not only is this insanely simple to do, it adds a lot of other advantages:
- Can send what page the user is on if the user is on "System" to get better help from the userguide
- Can be used to collect feedback (and what kinds of system questions users ask)
- much better than having them email me (which no one has done btw)
- Can easily customize the chatbot prompt or give suggested questions
Collaborated ideas with @wskksw 
NOTE that there is a new .env …
=> System Chatbot

packages/frontend/app/components/HeaderBar.tsx
- [added a back button to the /profile page](https://github.com/ubco-db/helpme/pull/248/commits/3e21d5985225345151e791fa9eaf9b70619d0642)
- [made mobile nav drawer close auotmatically after navigating](https://github.com/ubco-db/helpme/pull/248/commits/7d7d94704a2801998175266cbbeb57f38d57a3f5)
here's a pick of the back button
manual testing i'm lazy and don't want to write everything i tried but i tried a lot of things
=> Navbar small improvements

packages/common/index.ts, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/check_in/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/schedule/components/EventTooltip.tsx, packages/frontend/app/(dashboard)/course/[cid]/schedule/components/StudentSchedulePanel.tsx, packages/frontend/app/(dashboard)/course/[cid]/schedule/components/TASchedulePanel.tsx, packages/frontend/app/(dashboard)/course/[cid]/schedule/page.tsx, packages/frontend/app/typings/types.ts, packages/server/src/calendar/calendar.controller.ts
Adds some pretty tooltips when you hover an event. This also adjusts the content body of the event to show more details like the location and location type.
This popconfirm was added to prevent accidentally hovering and clicking the link unintentionally.
It also shows assigned staff (if there are any)
This also adds tooltips to the TA Checkin Out Page
And you bet it works on mobile (it will just be on-tap rather than on-hover)
Closes #212 
This is mostly just a frontend change so a lot of manual testing. This includes seeing how the tooltips behave on desktop and mobile for both staff and students.
=> Event Details Tooltip

packages/frontend/public/changelog.md
Just putting it in a PR in advance 'cause I can
=> 1.4 changelog

packages/server/src/lmsIntegration/lmsIntegration.service.ts
Tiny Bugfix for LMS Individual Doc Sync/clear
* Literally just two lines of code
No tests
=> Tiny Bugfix for LMS Individual Doc Sync/clear

packages/server/src/lmsIntegration/lmsIntegration.service.ts
Tiny fix to add the HMS API key to the LMS Integration service functions that contact the chatbot.
Manual testing
=> Bug Fix: LMS Integration Routes Inaccessible

packages/frontend/app/(auth)/verify/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/(insights)/layout.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/layout.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/components/QueueChat.tsx, packages/frontend/app/(dashboard)/layout.tsx, packages/frontend/app/(dashboard)/organization/course/[courseId]/edit/page.tsx, packages/frontend/app/(dashboard)/organization/course/add/page.tsx, packages/frontend/app/(dashboard)/organization/user/[userId]/edit/page.tsx, packages/frontend/app/api/userApi.ts, packages/frontend/app/invite/page.tsx, packages/frontend/app/qi/[qid]/page.tsx, packages/frontend/middleware.ts, packages/frontend/middlewareType.ts
Just some small changes that add better error checking to getUser. Haven't tested it yet
=> made getUser error checking better

packages/common/index.ts, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/lms_integrations/components/LMSDocumentList.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/lms_integrations/page.tsx, packages/frontend/app/api/index.ts, packages/server/src/lmsIntegration/lmsCourseIntegration.entity.ts, packages/server/src/lmsIntegration/lmsIntegration.controller.ts, packages/server/src/lmsIntegration/lmsIntegration.service.ts
Added this LMS resource type selector that lets the instructor select the type of resource they want the chatbot to have access to.
TODO: ~~hv to fix the UI for mobile, will remove this note when completed :)~~
TODO: ~~also have to make the checkboxes persist state across renders~~
TODO: write integration tests
Edit: Also made this UI change to the individual document selector
Closes #303 
Manually for now but going to write integration tests as well.
=> LMS Resource Type Selector

packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_settings/page.tsx
implemented the pagination in the chatbot settings for the document aggregates
=> [bugfix] pagination on chatbot settings

packages/server/src/asyncQuestion/asyncQuestion.service.ts
made anytime question emails no longer await so the emails happen asyncronously. Just wanted to make a quick PR for it to make sure it doesn't break a random test
=> Async Anytime Emails

packages/frontend/app/(dashboard)/organization/components/CoursesTable.tsx, packages/server/src/organization/organization.service.ts
Small change to allow searching for courses in course list by ID and showing ID in said list 
Closes #317
Manually :)
=> Show course Ids on organization course list

packages/common/index.ts, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/modals/AddStudentsToQueueModal.tsx, packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx, packages/frontend/app/api/index.ts, packages/server/src/guards/role.guard.ts, packages/server/src/question/question.controller.ts, packages/server/test/lmsIntegration.integration.ts, packages/server/test/question.integration.ts, packages/server/test/util/testUtils.ts
Realised some of the question controller endpoints were unprotected.
Added some new tests. Didn't manually test though. But if the tests pass it should be fine
=> Updated question controller protections

packages/frontend/app/(auth)/login/page.tsx, packages/frontend/app/(auth)/password/page.tsx, packages/frontend/app/(auth)/register/page.tsx, packages/frontend/app/(dashboard)/components/CourseCloneForm.tsx, packages/frontend/app/(dashboard)/components/coursesSection.tsx, packages/frontend/app/(dashboard)/course/[cid]/(insights)/components/InsightsPageMenu.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_knowledge_base/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_questions/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_settings/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/edit_questions/page.tsx, packages/frontend/app/(dashboard)/course/[cid]/components/popularTimes/TimeGraph.tsx, packages/frontend/app/components/Markdown.tsx, packages/frontend/app/error_pages/429/page.tsx, packages/frontend/app/utils/notificationUtils.ts, packages/server/migration/1754674227231-entity-enum-and-type-fixes.ts, packages/server/migration/1755999708148-lms-page-body-drop-not-null.ts, packages/server/src/course/course.controller.ts, packages/server/src/factory/factory.service.ts, packages/server/src/question/question.controller.ts
Fixing some build errors (not really just TypeScript not implicitly supporting certain JSX features so using expect-error) & updating migrations in preparation for a new release
Manually
=> Fix Build Errors & Update Migrations

packages/server/src/lmsIntegration/lmsIntegration.adapter.ts
Pages were being loaded in that shouldn't be accessible.
Current implementation will destroy these persisted items when the items refresh at midnight, so there's no worries about clearing data on prod.
Manually
=> Check Canvas Pages for 'Published' flag

packages/frontend/app/(dashboard)/components/FooterBar.tsx, packages/frontend/public/changelog.md
=> v1.6 changelog 

packages/server/src/chatbot/chatbot.controller.ts, packages/server/src/interceptors/IgnoreableClassSerializerInterceptor.ts
Ignoreable class serializer to be used on routes that (return files) because the serializer doesn't like it when those routes error.
Manual testing
=> Ignoreable Class Serializer

docs/NEWDEVS_STARTHERE.md, packages/frontend/app/(dashboard)/components/FooterBar.tsx, packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_knowledge_base/page.tsx, packages/frontend/public/changelog.md, packages/server/src/insights/insight-objects.ts, packages/server/test/__snapshots__/insights.integration.ts.snap
See files changed, not a lot to say here.
=> Changelog v1.7.0 + rename to "Usage Over Time" graph
