- packages/app/styles/global.css
Rainbow border might be irritating for some users, so this adds a media query for `prefers-reduced-motion` that makes it a static blue border.
It will remain the same for most users.
Note: This actually applies to all uses of the `glowy` class (the class that adds the glowy border), but it's only used on the queue cards right now.
With prefers-reduced-motion on (static)
With prefers-reduced-motion off (default). Same rainbow border as before
Manual testing. I used chrome dev tools' "emulate prefers-reduced-motion environment" to see what it would look like.
> added prefers-reduced-motion blue border for the queue card

- package.json
- packages/server/package.json
Hopefully makes it so `yarn dev` works on windows while also not breaking mac/unix.
@d3li0n @wskksw please test on your end, i don't want this to break your environment
> Fix Windows yarn dev

- packages/app/components/Questions/AsyncQuestions/AsyncCard.tsx
- packages/app/components/Questions/AsyncQuestions/TAanswerQuestionModal.tsx
- packages/app/components/Questions/AsyncQuestions/TAquestionDetailButtons.tsx
- packages/server/src/asyncQuestion/asyncQuestion.controller.ts
- packages/server/test/asyncQuestion.integration.ts
- Fixes async questions getting banished from redis when updated
- Fixed async questions not getting refreshed when a response is posted
- Fixed TA deleting a question calling an undefined function
- Fixed clicking anywhere on the "post response" card causing the async question card to expand/unexpand
- Fixed professors from being unable to update an async question if they are a student in another course (with a new test to check for that)
> Async Centre fixes

- packages/app/next.config.js
- packages/app/pages/_app.tsx
- packages/server/src/bootstrap.ts
We're not using sentry right now, so we're disabling it temporarily
> disable sentry when NODE_ENV === production

- README.md
- docs/taskQuestions_Demos_Assignments_TaskProgress_help.md
- packages/common/index.ts
- packages/server/src/alerts/alerts.controller.ts
- packages/server/src/asyncQuestion/asyncQuestion.controller.ts
- packages/server/src/auth/auth.controller.ts
- packages/server/src/calendar/calendar.controller.ts
- packages/server/src/chatbot/chatbot.controller.ts
- packages/server/src/course/course.controller.ts
- packages/server/src/course/course.service.ts
- packages/server/src/insights/insights.controller.ts
- packages/server/src/organization/organization.controller.ts
- packages/server/src/question/question.controller.ts
- packages/server/src/questionType/questionType.controller.ts
- packages/server/src/queue/queue.controller.ts
- packages/server/src/studentTaskProgress/studentTaskProgress.controller.ts
- packages/server/test/organization.integration.ts
Adds ParseIntPipe to all endpoints that use `@Param` with an id/number of some kind. Without this pipe, `@Param` will allow strings and can cause backend stuff to error or crash.
I don't want to add like a million new tests but i did add one
> Fix endpoints allowing strings where numbers should be

- packages/server/src/organization/organization.controller.ts
more than one row returned by a subquery used as an expression" error. It sets the max_uses to 300 if the user has a professor role in any course, and to 30 otherwise.
> fix chat_token limit bug

- packages/server/src/auth/auth.service.spec.ts
- packages/server/src/auth/auth.service.ts
Right now, if you login with google to org A and then try to login with google (same account) to org B, you just get logged into org A again.
Can't really test this on dev that well so we're gonna test it on prod later tonight
> Fix login with google not working with multiple organizations

- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx
- packages/frontend/app/(dashboard)/profile/components/ProfileSettings.tsx
- packages/frontend/app/(dashboard)/profile/components/SettingsMenu.tsx
Made redirect to notifications section of profile work as intended (opens the notification tab by default in profile page) when student asks their first question on the website and clicks on the associated dialog.
* Simple changes to `[qid]/page.tsx` to redirect to profile page directly to the notifications tab/subpage
* Support for this via use of search params in the profile page
* Settings buttons now has parameter for the 'currentSettings' passed down so the correct button is highlighted
* Added same functionality for 'preferences' tab in case a redirect to that will be used in the future
Closes #60
Manually tested by logging in on one browser as an instructor, opening a queue, then opening another browser as a student, joining the queue, and selecting the option to turn on …
> Redirection to notification page from queue page fix

- packages/common/index.ts
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/queue_invites/components/QueueInvite.tsx
- packages/frontend/app/qi/[qid]/page.tsx
- packages/server/src/queue/queue-invite.controller.ts
- packages/server/src/queue/queue.service.ts
- packages/server/test/queue-invite.integration.ts
This changes queue invite codes to be encoded in base64 rather than simple encodeURIComponent.
Why? So that professors can put special characters inside the queue invite code without a bunch of stuff breaking.
I also fixed a bug where it wasn't enrolling the person if they were already logged in.
**I need this merged before anyone makes any links**
I did some manual testing and everything seems to work fine.
> Queue invite code base64 encoding

- docs/ENVIRONMENT_VARIABLES.md
- packages/frontend/app/api/cookieApi.ts
The system won't redirect you to the queue invite page after registering with google for some reason. 
I am unsure if this actually fixes it, I am unable to test if google oath works on localhost
> Hopefully fix redirect to queue invite page after registering with google

- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/StudentBanner.tsx
- packages/frontend/app/(dashboard)/layout.tsx
Adds a few more loading states, which should make some buttons feel a bit more responsive to click for students.
Manually tested each button that was changed. Also looked at every page again to make sure nothing broke by adding flex-grow.
> More loading states for buttons

- packages/server/src/asyncQuestion/asyncQuestion.controller.ts
- packages/server/src/mail/mail.service.ts
This PR addresses two issues:
1. Prevent duplicate notifications for async questions:
- Modified the user subscription query to group by user ID, ensuring each user receives only one notification per flagged question.
- Added logging to track subscription counts and email sending for better debugging.
- Removed redundant Redis queue update to prevent potential duplication.
2. Add unsubscribe option to all outgoing emails:
- Updated the `sendEmail` function in the mail service to consistently append "View Your Courses" and unsubscribe links to all emails.
Changes:
- Updated `updateStudentQuestion` endpoint in async questions controller
- Modified `sendEmail` function in mail service
Provide instructions so we can …
> Fix duplicate notifications and add unsubscribe option to all emails

- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_settings/page.tsx
add toggle to enable parse slides from document
Closes #118
> add toggle to enable parse slides from document

- packages/common/index.ts
- packages/frontend/app/(dashboard)/components/EditCourseForm.tsx
- packages/frontend/app/api/index.ts
- packages/server/src/organization/organization.controller.ts
Before
After (you can also now actually click the update button and it will work)
Closes #158 
Just a bit of manual testing with updating the course with some of these non-org profs and updating the course with only org profs
> Fix bug where users cannot update a course if a user is promoted to a professor through the course roster page

- packages/server/src/organization/organization.controller.ts
- packages/server/src/profile/profile.controller.ts
Just a small patch to allow for users and organizations with out-of-sync database references to images in the ```./uploads``` directory to still change their avatars and organization banners and logos.
This is what gets logged when this occurs in the backend's console (should still never happen, but if it does, there's a way to track it down):
> Image Resource Desync (Uploads Directory and Database Image URLs)

- packages/common/index.ts
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/CircleButton.tsx
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/QuestionCard.tsx
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/QueueQuestions.tsx
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/StaffList.tsx
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/StudentBanner.tsx
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/TAQuestionCardButtons.tsx
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/utils/commonQueueFunctions.ts
- packages/frontend/app/qi/[qid]/components/QuestionCardSimple.tsx
- packages/frontend/app/qi/[qid]/page.tsx
- packages/frontend/app/utils/timeFormatUtils.ts
- packages/server/migration/1729450514047-paused-at-property-question-model.ts
- packages/server/src/notification/notification.service.ts
- packages/server/src/question/question-fsm.ts
- packages/server/src/question/question.entity.ts
- packages/server/src/question/question.service.ts
- packages/server/src/queue/queue.service.spec.ts
- packages/server/src/queue/queue.service.ts
- packages/server/test/question.integration.ts
Added ability for queue staff to 'pause' questions after they've been helped, in order to help more high-priority questions.
The question itself remains considered to be being helped - it is not moved back into the queue. While paused, a timer indicating how much time has elapsed since the question was paused is visible.
Additionally, other queue staff can pick up paused questions in case they clear up. This provides a method for queue staff to delay responding to certain questions in case of higher priority ones entering the queue, while also keeping the student on the top of the heap of questions to handle.
Changes to the 'helpedAt' column are made. Question entity now has an attribute 'pausedAt' that is essentially a temporary time-tracker and removed after the question is unpaused. …
> Pause Questions

- packages/server/migration/1729547252435-question-type-not-nullable.ts
- packages/server/src/questionType/question-type.entity.ts
Small change.
Note that before this gets put on production, the following command should be ran:
`UPDATE question_type_model SET name = 'was null', "deletedAt" = NOW() WHERE name IS NULL`
Normally we could just set up a migration for this. However, we don't actually have migrations set up on prod.
> made question type name, color, cid not nullable

- packages/common/index.ts
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/QuestionCard.tsx
- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/components/StudentBanner.tsx
- packages/frontend/app/qi/[qid]/components/QuestionCardSimple.tsx
- packages/frontend/app/qi/[qid]/page.tsx
- packages/frontend/app/utils/timeFormatUtils.ts
- packages/server/migration/1731187674872-accurate-helptimes-waittimes.ts
- packages/server/package.json
- packages/server/src/insights/insight-objects.ts
- packages/server/src/insights/insights.service.spec.ts
- packages/server/src/question/question.controller.ts
- packages/server/src/question/question.entity.ts
- packages/server/src/question/question.service.spec.ts
- packages/server/src/question/question.service.ts
- packages/server/src/queue/__snapshots__/queue.service.spec.ts.snap
- packages/server/src/queue/queue.entity.ts
- packages/server/src/queue/queue.service.ts
- packages/server/test/__snapshots__/queue.integration.ts.snap
- packages/server/test/jest-integration.json
- packages/server/test/question.integration.ts
- yarn.lock
This is a really important PR that should be merged before we update prod with pause questions (#175 ) and the requeueing stuff in the queue locations one (#148). About 5% of questions have a helpedAt != firstHelpedAt, and these two PRs are going to increase that dramatically. And previously, any time that a question is helped more than once, it is impossible to properly calculate the waitTIme and helpTime.
Fixes
- You can now repeatedly pause/unpause a question and the waitTime and helpTime will be properly updated
- the wait time on question cards will no longer increase while the student is being helped or drafting or being requeued (because previously it wasn't the wait time, it was just the question's lifespan)
- Paused questions are now included in queueSize
- centralised the …
> More Accurate waitTimes and helpTimes

- packages/frontend/public/changelog.md
- packages/server/src/backup/backup.service.spec.ts
- packages/server/src/backup/backup.service.ts
A simple bug fix that makes it so deleteOldBackups ignores .md files
Added some tests for it but haven't yet done manual testing (it would be kinda hard to manually test)
> deleteOldBackups ignore .md files

- packages/frontend/app/(dashboard)/course/[cid]/(insights)/insights/page.tsx
- packages/server/src/insights/insight-objects.ts
- packages/server/src/insights/insights.service.spec.ts
I just made the insights page show all insights by default (kind of removes the purpose of the categories, but done by request)
Also removed the most active students table showing the emails & IDs as these are kind of unnecessary points to show that data
No related issue(s)
Altered existing unit/integration tests where necessary
> Populate Default Insights Page

- packages/server/src/backup/backup.service.ts
This change fixed the backend service for upload directory backups so that it no longer deletes the last two days of backups (all other backups). Just to give context to those not aware, this backup function should be run every 4 days and save the last three (12 days).
> Uploads Backup Deletion Bugfix

- packages/common/index.ts
- packages/server/src/decorators/course-role.decorator.ts
- packages/server/src/decorators/course-roles.decorator.ts
- packages/server/src/decorators/org-roles.decorator.ts
- packages/server/src/decorators/roles.decorator.ts
- packages/server/src/guards/org-or-course-roles.guard.ts
- packages/server/src/guards/organization-roles.guard.ts
- packages/server/src/guards/role.guard.ts
- packages/server/src/organization/organization.controller.ts
- packages/server/test/organization.integration.ts
Creates a new guard that allows you to specify an endpoint where the user needs either the right course role or the right org role
- it does two queries simultaneously to check if they either have the right org role or the right course role (for the given course)
**This also fixes some access problems where some endpoints would error for course profs**:
- deleteUserCourses (used to remove students from your course)
- getOrganizationCourse (used when the staff goes on any page to edit a course)
- updateCourse (used when prof wants to update their course details)
Another piece of motivation for creating this guard is it will make it easier to extend admin permissions so that they can call more endpoints without being in a course (for the future)
Here is an example of a course professor …
> OrgOrCourseRolesGuard + Allow Course Profs to Edit Their Courses

- packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx
fixed chatbot resetting itself on page change. Also fixed the double allSuggestedQuestions calls
Some manual testing
> Chatbot small bug fixes

- packages/common/index.ts
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_document_chunks/components/ChunkHelpTooltip.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_document_chunks/components/EditChatbotDocumentChunkModal.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_document_chunks/page.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_questions/components/AddChatbotQuestionModal.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_questions/components/EditChatbotQuestionModal.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_questions/page.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_settings/components/AddChatbotDocumentModal.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_settings/components/ChatbotSettingsModal.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_settings/page.tsx
- packages/frontend/app/(dashboard)/course/[cid]/async_centre/components/modals/ConvertChatbotQToAnytimeQModal.tsx
- packages/frontend/app/(dashboard)/course/[cid]/async_centre/components/modals/CreateAsyncQuestionModal.tsx
- packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx
- packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Feedback.tsx
- packages/frontend/app/api/index.ts
- packages/frontend/app/typings/chatbot.ts
- packages/server/.env.development
- packages/server/.env.docker
- packages/server/src/chatbot/chatbot-api.service.ts
- packages/server/src/chatbot/chatbot.controller.ts
- packages/server/src/chatbot/chatbot.module.ts
- packages/server/src/chatbot/chatbot.service.spec.ts
- packages/server/src/chatbot/chatbot.service.ts
- packages/server/src/chatbot/interaction.entity.ts
- packages/server/src/chatbot/question.entity.ts
- packages/server/src/guards/course-roles-helpme-bypass.guard.ts
- packages/server/test/chatbot.integration.ts
So the problem with the current token system is you just need to be logged in to get a token (and thus call any chatbot endpoint).
So, for example, i could just create an account (and never join any course) and then call the endpoints that delete all chatbot data for all of the courses (because that's an endpoint on the chatbot apparently lol).
So there are no role guards basically, nor any course guards (so i can access documents in questions in courses that i am not in).
So by adding a new chatbot api key (that only the backend of helpme has), users can't just call the chatbot endpoints directly, they have to go through the helpme system first (in which i can use CourseRolesGuard to protect the endpoints)
This also:
- Adjusts/adds more tooltips for helping users around the chatbot
- …
> Fix Security on Chatbot Routes

- packages/frontend/app/invite/components/InviteCard.tsx
- packages/frontend/app/invite/page.tsx
Fixes Issue #273
Adds a "Decline Invitation Button" to the invite page taking the user back to the `/courses` route.
Achieved by adding 2 optional (`secondaryButtonLabel` and `secondaryButtonAction`) props to the  `InviteCard` component which only renders if both the label and the action is provided.
No new dependencies required
Closes #273 
Provide instructions so we can reproduce. 
I logged in with an account with no courses and with the UBCO Organization, then went to `/invite?cid=37&code=invite-code` route on localhost, which is the invite link for CS 304 in the UBCO Org, then manually tested it.
> fix(invite): add option to decline course invitation (#273)

- docs/NEWDEVS_STARTHERE.md
- packages/server/src/course/course.controller.ts
- packages/server/src/course/course.module.ts
- packages/server/src/course/course.service.ts
- packages/server/src/course/course.subscriber.ts
- packages/server/src/notification/desktop-notif-subscriber.ts
- packages/server/src/notification/notification.module.ts
- packages/server/src/organization/organization-user.subscriber.ts
- packages/server/src/organization/organization.controller.ts
- packages/server/src/organization/organization.module.ts
- packages/server/src/profile/profile.controller.ts
- packages/server/src/profile/profile.module.ts
- packages/server/src/profile/profile.service.spec.ts
- packages/server/src/profile/profile.service.ts
- packages/server/src/profile/profile.subscriber.ts
- packages/server/src/profile/user-course.subscriber.ts
- packages/server/src/profile/user-token.subscriber.ts
- packages/server/src/profile/user.entity.ts
- packages/server/src/semester/semester.module.ts
- packages/server/src/semester/semester.subscriber.ts
So I found a bug where after creating an account and verifying my email, it doesn't clear the redis profile cache so I am just stuck there waiting for the 30mins or whatever for the cache to bust itself (also for more context, the redis profile caching is NOT on prod yet, so no actual users were affected by this bug).
And so rather than just adding another cache bust to that endpoint, I remembered that we have these typeorm EventSubscribers that we can use to connect database events with external systems. 
So, I opted to remove all manual cache busting and instead added EventSubscribers for all relevant updates so that they bust the caches automatically whenever they update.
Not only does this fix any cases we might've missed with the original redis profile cache, but this will also make …
> Improve RedisProfile Cache Busting

- packages/frontend/app/(dashboard)/course/[cid]/queue/[qid]/page.tsx
Hopefully fixes the issue with the Enable Notifications popup showing up more than once. Always sets the localStorage value to false after creating a question; note that since it's localStorage it's not going to replicate across devices, but at least we don't need another DB column.
Closes #183 
Manually
> Bug Fix: 'Enable Notifications' Popup

- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_settings/components/AddChatbotDocumentModal.tsx
- packages/frontend/app/contexts/AsyncToasterContext.tsx
Refactors the AddChatbotDocumentModal to use AsyncToaster to asynchronously run toaster messages. It also does all uploads in parallel now rather than one-at-a-time
Now the user won't be stuck in the UI waiting for their chatbot documents to upload (notice how the notification here popped up even though i was on another page)
also the errors show up indefinitely until dismissed so you can go afk and come back and not miss anything
and it will show in the modal as well (though that only works if they haven't left the page)
Manual testing
> Improve UX for Chatbot Document Upload

- packages/common/index.ts
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_questions/page.tsx
- packages/frontend/app/(dashboard)/course/[cid]/async_centre/components/AsyncQuestionCard.tsx
- packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx
- packages/server/src/asyncQuestion/asyncQuestion.service.ts
Deepseek think block was being sent in anytime question response email
Manually
> [bugfix] Remove think block before sending AQ email

- packages/common/index.ts
- packages/frontend/app/(dashboard)/components/EditCourseForm.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/components/CourseRosterTable.tsx
- packages/server/src/course/course.service.ts
- packages/server/src/organization/organization.controller.ts
- packages/server/test/organization.integration.ts
- yarn.lock
Crown icon next to admin names in professor selector + course roster
Professor selector was already an admin-only interface but I modified the backend logic to support that (prevent accidental mistakes)
Also made the organization course update route handler only do promotion/demotion, noticed that when deleting from the selector it actually removes the user from the course, it now only demotes to student to prevent unintended removals
Closes #322
Updated associated integration test
Manually tested
> Highlight admins in professor selector and course roster

- packages/common/index.ts
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/lms_integrations/components/LMSDocumentList.tsx
- packages/server/migration/1755999708148-lms-page-body-drop-not-null.ts
- packages/server/src/chatbot/chatbot-datasource/chatbot-datasource.service.ts
- packages/server/src/chatbot/chatbot.service.ts
- packages/server/src/lmsIntegration/lmsIntegration.service.spec.ts
- packages/server/src/lmsIntegration/lmsPage.entity.ts
- packages/server/test/chatbot.integration.ts
* Improved course chatbot settings backfill to retain old parameters + model (if possible)
* Minor migration addition for the pages 'body' column being nullable
Manually
> Improved Course Chatbot Settings Backfill + Minor Migration Fix

- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_settings/components/ChatbotSettingsModal.tsx
- packages/frontend/app/(dashboard)/course/[cid]/(settings)/settings/chatbot_settings/page.tsx
- packages/frontend/app/(dashboard)/organization/ai/components/CourseSettingTable.tsx
- packages/frontend/app/(dashboard)/organization/ai/components/LLMTypeDisplay.tsx
- packages/frontend/app/(dashboard)/organization/ai/page.tsx
Removed the indicator that showed 'this model can process visual input' and 'this model can process text input' in course chatbot settings. Replaced simply with 'star' icon that shows up only if it's the default model for the organization's default provider
Closes #404 
It's pure frontend, so manual
> Remove chatbot modality indicators for course settings

- packages/frontend/app/(dashboard)/components/coursesSection.tsx
- packages/frontend/app/components/HeaderBar.tsx
TIL the default trigger behavior for any navigation item is onPointerEnter. Suppressed these events and now only triggering the dropdown onClick. 
Closes #400
> Trigger Profile/Queue dropdown on click only
